name = "KomaMRIFiles"
uuid = "fcf631a6-1c7e-4e88-9e64-b8888386d9dc"
authors = ["Carlos Castillo Passi <cncastillo@uc.cl>"]
version = "0.9.1"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
KomaMRIBase = "d0bc0b20-b151-4d03-b2a4-6ca51751cb9c"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MRIFiles = "5a6f062f-bf45-497d-b654-ad17aae2a530"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Scanf = "6ef1bc8b-493b-44e1-8d40-549aa65c4b41"

[compat]
FileIO = "1"
HDF5 = "0.16, 0.17"
InteractiveUtils = "1"
KomaMRIBase = "0.9"
MAT = "0.10"
MRIFiles = "0.1, 0.2, 0.3"
Reexport = "1"
Scanf = "0.5"
julia = "1.9"

[workspace]
projects = ["test"]
