version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
      - "/test"
      - "/benchmarks"
      - "/KomaMRIBase"
      - "/KomaMRIBase/test"
      - "/KomaMRICore"
      - "/KomaMRICore/test"
      - "/KomaMRIFiles"
      - "/KomaMRIFiles/test"
      - "/KomaMRIPlots"
      - "/KomaMRIPlots/test"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "julia"
