name = "KomaMRI"
uuid = "6a340f8b-2cdf-4c04-99be-4953d9b66d0a"
authors = ["Carlos Castillo Passi <cncastillo@uc.cl>"]
version = "0.7.4"

[deps]
AssetRegistry = "bf4720bc-e11a-5d0c-854e-bdca1663c893"
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
KomaMRICore = "4baa4f4d-2ae9-40db-8331-a7d1080e3f4e"
KomaMRIPlots = "76db0263-63f3-4d26-bb9a-5dba378db904"
MRIReco = "bdf86e05-2d2b-5731-a332-f3fe1f9e047f"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
AssetRegistry = "0.1"
Blink = "0.12"
Interact = "0.10"
KomaMRICore = "0.7"
MRIReco = "0.6, 0.7"
PlotlyJS = "0.18"
Reexport = "1"
julia = "1.6"
