name = "KomaMRI"
uuid = "6a340f8b-2cdf-4c04-99be-4953d9b66d0a"
authors = ["Carlos Castillo Passi <cncastillo@uc.cl>"]
version = "0.9.1"

[deps]
AssetRegistry = "bf4720bc-e11a-5d0c-854e-bdca1663c893"
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
KomaMRICore = "4baa4f4d-2ae9-40db-8331-a7d1080e3f4e"
KomaMRIFiles = "fcf631a6-1c7e-4e88-9e64-b8888386d9dc"
KomaMRIPlots = "76db0263-63f3-4d26-bb9a-5dba378db904"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MRIReco = "bdf86e05-2d2b-5731-a332-f3fe1f9e047f"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
AssetRegistry = "0.1"
Blink = "0.12"
FFTW = "1.0"
Interact = "0.10"
MAT = "0.10"
MRIReco = "0.6, 0.7, 0.8, 0.9"
Reexport = "1"
julia = "1.9"

[workspace]
projects = ["test", "docs", "benchmarks", "KomaMRIBase", "KomaMRICore", "KomaMRIFiles", "KomaMRIPlots"]
