[deps]
KomaMRI = "6a340f8b-2cdf-4c04-99be-4953d9b66d0a"
KomaMRICore = "4baa4f4d-2ae9-40db-8331-a7d1080e3f4e"
KomaMRIFiles = "fcf631a6-1c7e-4e88-9e64-b8888386d9dc"
KomaMRIPlots = "76db0263-63f3-4d26-bb9a-5dba378db904"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoPlotly = "8e989ff0-3d88-8e9f-f020-2b208a939ff0"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"

[compat]
julia = "1.9"