[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
KomaMRI = "6a340f8b-2cdf-4c04-99be-4953d9b66d0a"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NodeJS_16_jll = "a4b94fbf-73f5-58ff-888d-48a8396e17f6"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PlutoSliderServer = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4"

[compat]
Documenter = "1"
